version: '3'

services:
  web:
    build: .
    command: bash -c "python manage.py migrate &&
                      python manage.py collectstatic --noinput &&
                      python manage.py runserver 0.0.0.0:8000"
    expose:
      - 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/code
