version: '3'

services:
  web:
    build: .
    command: bash -c "python manage.py migrate &&
                      python manage.py collectstatic --noinput &&
                      python manage.py runserver 0.0.0.0:8000"
    expose:
      - 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - redis
    links:
      - redis:redis
    env_file:
      - .env

  worker:
    build: .
    volumes:
      - .:/code
      - ./logs/celery/:/var/log/celery/
    command: bash -c "celery -A kfc worker -E"
    env_file:
      - .env
    depends_on:
      - web

  beat:
    build: .
    volumes:
      - .:/code
      - ./logs/celery/:/var/log/celery/
    command: bash -c "celery -A kfc beat --loglevel=info"
    depends_on:
      - worker
    env_file:
      - .env

  redis:
    build:
      context: ./docker/redis
      dockerfile: Dockerfile
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./docker/redis/redis_data:/data
    expose:
      - "6379"
    ports:
      - "6379:6379"
    env_file:
      - .env
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass "${REDIS_PASSWORD}"
