# Generated by Django 3.2.19 on 2023-06-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
